services:
  waifu2x:
    image: kamilake/waifu2x-api-server
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8080:80"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always